  name: PyInstaller Linux
  on:
    release:
      types:
        - released                        # When new version of your action is released
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install uv
          uses: astral-sh/setup-uv@v6
        - name: Set up Python
          run: uv python install
        - name: Install the project
          run: uv sync --locked --all-extras --dev
        - name: Run PyInstaller
          run: uv run pyinstaller deepagents.spec
        - name: Create release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            body: |
              Test Relase v1
        - name: Upload Release Asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: dist/deepagents
            asset_name: deepagents
            asset_content_type: application/octet-stream
            

